# SPDX-FileCopyrightText: 2022 GitHub
# SPDX-FileCopyrightText: 2023 Freedom of the Press Foundation
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: npm check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run check
