# SPDX-FileCopyrightText: 2023 r2c <https://r2c.dev>
# SPDX-FileCopyrightText: 2023 Gonzalo Bulnes Guilpain
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# See https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/

name: Semgrep

on: push

jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    name: SAST Scan
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3
      # Run the "semgrep" command on the command line of the docker image.
      - run: semgrep --sarif --output semgrep.sarif
        env:
          # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
          SEMGREP_RULES: p/default # more at semgrep.dev/explore

      # Upload SARIF file generated in previous step
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
